### ISSUE TITLE
Could you add me on discord uniform#5344 or tell me how it works, im trying to figure out....

### ISSUE THREAD

**Issue by lamafa111** [TheGamer456YT/frick-discord-2fa#2]
Could you add me on discord uniform#5344 or tell me how it works, im trying to figure out but idk how to link it with
my account to start bruteforcing. thx

**Comment by SpaghettDev** [comment]
This repo contains only a script that can be used to generate discord 2fa codes to a file.

If you want a program to automatically bruteforce, then you're out of luck because [hydino](https://github.com/hydino2085143) (a previous contributor) used to have a program called Discord-OTP-Forcer that's based on this script, but looking for it now yields no result.

Update: look at the [comment below](https://github.com/TheGamer456YT/frick-discord-2fa/issues/2#issuecomment-1140403794).

**Comment by Derpitron** [comment]
I have unprivated my repository, it should be there on my profile. https://github.com/hydino2085143/Discord-OTP-Forcer @lamafa111
